#General configuration settings
[general]
	#A config option to help developers find known legacy modded tags that have common convention equivalents when running on integrated server. Defaults to OFF.
	#Allowed Values: OFF, ONLY_IN_DEV_ENV, ALWAYS
	logLegacyTagWarnings = "OFF"
